### ISSUE TITLE
Potentially add cards to Trello for assessments (and practices/labs?)

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/meta#11]
1. So we can track time
2. To make it obvious when we don't have lessons with assessments.

**Comment by jrhorn424** [comment]
Other candidates for their own cards include labs and practices. For many early practices, we already have cards, but we may need to add specific cards for future practices.

Note to self: Add cards for practices that we author as we go along.

**Comment by raq929** [comment]
We are no longer using Trello. Can this be closed?
