### ISSUE TITLE
Consider a naming convention for required/optional practices

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/meta#14]
Should we make a distinction between required and optional practices? For example, if we expect a pull request, I suggest naming the repo like `js-higher-order-functions-practice` or `js-higher-order-functions-challenge`. If we expect no pull request, such as when there are optional pre-readings, we could name the repo `js-higher-order-functions-study`.

**Comment by jrhorn424** [comment]
I think this has become clearer with use.

Practices are given in the evenings and involve some kind of coding, whether or not a PR is expected. I suggest that we shouldn't require pull requests for practice. This probably affects our nodeschool practices the most.

Studies are given in the evenings and involve some sort of reading or other self-study, like a tutorial.

**Comment by gaand** [comment]
:+1:
