### ISSUE TITLE
Should "practice"s be renamed "challenge"?

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/meta#15]
This would be to emphasize that students: (1) may not complete the assignment and (2) may not have had all the necessary instruction to complete the assignment (i.e., they may need to do a bit of research).

**Comment by GA-MEB** [comment]
I think this is a reasonable idea. It also frees us up a bit to throw more difficult problems at them every so often, since it isn't expected that they'll always finish.
