### ISSUE TITLE
Prefer the use of `api` over `back-end` and `client` over `front-end`

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/meta#17]
To ease confusion students have over what "front-end" means, let's make it clear that it encompasses the entire browser-stack, including frameworks and tooling.

We already do something similar with `api`.

Related: #16

**Comment by GA-MEB** [comment]
Wondering if this might create confusion when we refer to APIs of specific programs (e.g. ActiveRecord, Mongoose).

**Comment by gaand** [comment]
API is a ubiquitous and fluid term.  A little confusion may be unavoidable.

**Comment by raq929** [comment]
Documented: https://github.com/ga-wdi-boston/instructors/wiki/Profanity

**Comment by gaand** [comment]
@jrhorn424 Closing to ease the load.
