### ISSUE TITLE
Rename assessments to something else - possibly 'diagnostics'?

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/meta#20]

**Comment by jrhorn424** [comment]
I'm willing to try this immediately, or during the next cohort.

**Comment by gaand** [comment]
I favor next cohort.  Fresh start.

**Comment by raq929** [comment]
I feel like this issue has been addressed... where should it be documented?

**Comment by raq929** [comment]
Documented: https://github.com/ga-wdi-boston/instructors/wiki/Profanity
