### ISSUE TITLE
Position of sequence number in repository name

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/meta#9]
I think it goes after topic and before type (at least in the situation I find myself in, i.e. js-basics-2-practice).

**Comment by jrhorn424** [comment]
You're correct. In the future, let's see if we can use different names than sequence numbers.

`js-basics-primitives`
`js-basics-references`
`js-basics-assessment` or `js-basics-references-assessments`

We've already discussed this of course, just noting it here for posterity.
